import os
from dotenv import load_dotenv

load_dotenv()

BLACKBOARD_BASE_URL = os.getenv("BLACKBOARD_BASE_URL")
BLACKBOARD_CLIENT_ID = os.getenv("BLACKBOARD_CLIENT_ID")
BLACKBOARD_CLIENT_SECRET = os.getenv("BLACKBOARD_CLIENT_SECRET")

INSPERA_BASE_URL = os.getenv("INSPERA_BASE_URL")
INSPERA_API_KEY = os.getenv("INSPERA_API_KEY")
INSPERA_CLIENT_ID = os.getenv("INSPERA_CLIENT_ID")


INSPERA_LTI_DEPLOYMENT_ID = os.getenv("INSPERA_LTI_DEPLOYMENT_ID")
